{{- range $name, $cfg := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  {{- with $cfg.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    {{- with $cfg.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
