---
bases:
  - ../../../bases/clusters.yaml

values:
  - app: gateway-api
    hierarchy:
      - environment
---
bases:
  - ../../../bases/releases.yaml.gotmpl

releases:
  - name: gateway-api-crds
    chart: ../../../charts/gateway-api-crds
