{{- range $name, $gateway := .Values.gateways }}
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: gateway-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selfManaged: false
  kube:
    service:
      type: NodePort
      ports:
        - port: {{ $gateway.listeners.https.port }}
          nodePort: {{ $gateway.listeners.https.nodePort }}
        - port: {{ $gateway.listeners.http.port }}
          nodePort: {{ $gateway.listeners.http.nodePort }}
{{- end }}
