---
bases:
  - ../../../bases/clusters.yaml

values:
  - hierarchy:
      - environment
---
bases:
  - ../../../bases/releases.yaml.gotmpl

releases:
  - name: cert-manager
    chart: oci://quay.io/jetstack/charts/cert-manager
    namespace: cert-manager
    version: v1.20.3

  - name: cert-manager-issuers
    chart: ../../../charts/raw
    namespace: cert-manager
