{{- range $name, $cfg := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  {{- with $cfg.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $cfg.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
