namespaces:
  cert-manager: {}
  external-secrets: {}
  headlamp: {}
  kgateway-system: {}

projects:
  core:
    allowedNamespaces:
      - cert-manager
      - external-secrets
      - kgateway-system
  aux:
    allowedNamespaces:
      - headlamp
  apps:
    allowedNamespaces:
      - "!kube-node-lease"
      - "!kube-public"
      - "!kube-system"

apps:
  repoURL: https://github.com/jace-ys/homelab.git

  watchedDirs:
    - path: kubernetes/apps/*/*
    - path: kubernetes/apps/00-init/argocd
      exclude: true

  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;/kubernetes/charts;/kubernetes/bases
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
