controller:
  priorityClassName: system-cluster-critical

  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 128Mi
