---
bases:
  - ../../../bases/clusters.yaml
---
bases:
  - ../../../bases/releases.yaml.gotmpl

releases:
  - name: argocd-init
    chart: ../../../charts/argocd-init

  - name: argocd-routes
    chart: ../../../charts/raw
    namespace: argocd
